config/routes.rb
# frozen_string_literal: true

# == Route Map
#

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "projects#index"

  resources :projects do
    member do
      post :sync
      get :configure
    end

    collection do
      get :user
    end

    resources :members, only: %i[index], controller: "project_members"
    resources :invitations, only: %i[index new create destroy], controller: "project_invitations"
    resource :accept_invitations, only: [:show], controller: "project_accept_invitations" do
      member do
        post :join
      end
    end

    resources :branches, only: [:index, :show], constraints: { id: %r{[^/]+} } do
      member do
        post :sync
        post :commit_create
        get :commits
      end
    end

    resources :pull_requests, only: [:index, :show] do
      member do
        post :sync
        post :commit_create
        get :commits
      end
    end

    resources :proposals
  end
  resource :connections, only: :show do
    get "/github/callback", to: "connections#github_callback"
    delete :disconnect_github
    post :request_sync
  end

  authenticate :user, ->(user) { user.admin? } do
    mount GoodJob::Engine => "good_job"
  end
end

app/models/branch.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: branches
#
#  id         :bigint           not null, primary key
#  name       :string
#  ref        :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  project_id :bigint           not null
#
# Indexes
#
#  index_branches_on_name_and_project_id  (name,project_id) UNIQUE
#  index_branches_on_project_id           (project_id)
#
# Foreign Keys
#
#  fk_rails_...  (project_id => projects.id)
#
class Branch < ApplicationRecord
  include Syncable
  belongs_to :project

  has_many :translations, ->(x) { where("? = ANY (branch_refs)", x.ref) }, foreign_key: :project_id, primary_key: :project_id
  has_one :sync_state, as: :syncable, dependent: :delete

  validates :name, presence: true, uniqueness: { scope: :project_id }

  def to_param
    name
  end

  def url
    File.join(Babelfu.config.github_domain, project.remote_repository_id, "tree", name)
  end

  def enqueue_sync!
    sync_in_progress!
    SyncBranchJob.enqueue_batch(project, name)
  end

  def broadcast_update_sync_status
    broadcast_update(renderable: SyncBranchWidgetComponent.new(self, live: true))
  end

  def sync_ref
    ref
  end
end

app/controllers/branches_controller.rb
# frozen_string_literal: true

class BranchesController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :find_project
  after_action :verify_authorized

  def index
    authorize @project, :explore?
    @branches = @project.branches.page(params[:page]).order(updated_at: :desc)
  end

  def show
    find_branch
    authorize @project, :explore?

    @translations_presenter = TranslationsPresenter.new(@project,
                                                        branch_name: @branch.name,
                                                        **params.to_unsafe_h.merge(filter_locales: filter_locales))
  end

  def sync
    find_branch
    authorize @project, :sync?

    @branch.enqueue_sync!
  end

  def commits
    find_branch
    authorize @project, :commit?
    @commits_presenter = CommitsPresenter.new(project: @project, branch_name: @branch.name)
  end

  # TODO: DRY this up with pull requests controller
  def commit_create
    find_branch
    authorize @project, :commit?

    @commit_task = @project.commit_tasks.build
    @commit_task.branch_name = @branch.name

    if @commit_task.save
      CommitJob.enqueue_batch(@commit_task)
      flash[:notice] = "Commit task created"
    else
      flash[:error] = "There was an error creating the commit task"
    end

    redirect_to commits_project_branch_path(@project, @branch)
  end

  private

  def find_branch
    @branch = @project.branches.find_by(name: params[:id])
  end

  def find_project
    @project = Project.find_by!(slug: params[:project_id])
  end
end

app/views/branches/commits.html.haml
.d-flex.justify-content-between.mb-3.align-items-start
  .div
    %nav{"aria-label" => "breadcrumb"}
      %ol.breadcrumb
        %li.breadcrumb-item
          = link_to "Projects", projects_path
        %li.breadcrumb-item
          = link_to @project.name, project_path(@project)
        %li.breadcrumb-item{"aria-current" => "page"}
          = link_to @branch.name, project_branch_path(@project, @branch)
        %li.breadcrumb-item.active{"aria-current" => "page"} Commit changes

= render CommitsComponent.new(presenter: @commits_presenter, create_commit_path: commit_create_project_branch_path(@project, @branch))

app/views/branches/index.html.haml
.d-flex.justify-content-between.mb-3.align-items-start
  .div
    %nav{"aria-label" => "breadcrumb"}
      %ol.breadcrumb
        %li.breadcrumb-item
          = link_to "Projects", projects_path
        %li.breadcrumb-item
          = link_to @project.name, project_path(@project)
        %li.breadcrumb-item.active{"aria-current" => "page"} Branches

.col-md-6
  .d-flex.justify-content-between.align-items-end
  - if @branches.empty?
    %p No branches
  - else
    %ul.list-group
      - @branches.each do |branch|
        %li.list-group-item.d-flex.justify-content-between.align-items-center
          = link_to branch.name, project_branch_path(@project, branch), class: 'text-decoration-none'

= paginate @branches, theme: 'bootstrap-5'

app/views/branches/show.html.haml
= turbo_stream_from @branch
.d-flex.justify-content-between.mb-3.align-items-start
  .div
    %nav{"aria-label" => "breadcrumb"}
      %ol.breadcrumb
        %li.breadcrumb-item
          = link_to "Projects", projects_path
        %li.breadcrumb-item
          = link_to @project.name, project_path(@project)
        %li.breadcrumb-item.active{"aria-current" => "page"}= @branch.name
    %h1.fs-3.mb-0 Translations
  .actions.d-flex.flex-row.align-items-end
    .me-5= render GithubLinkComponent.new(@branch.url)
    = link_to "Commit", commits_project_branch_path(@project, @branch), class: 'btn btn-primary me-2'

    %div{id: dom_id(@branch)}
      = render SyncBranchWidgetComponent.new(@branch)

= render BranchTranslationsComponent.new(@branch, @translations_presenter)