config/routes.rb
# frozen_string_literal: true

# == Route Map
#

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "projects#index"

  resources :projects do
    member do
      post :sync
      get :configure
    end

    collection do
      get :user
    end

    resources :members, only: %i[index], controller: "project_members"
    resources :invitations, only: %i[index new create destroy], controller: "project_invitations"
    resource :accept_invitations, only: [:show], controller: "project_accept_invitations" do
      member do
        post :join
      end
    end

    resources :branches, only: [:index, :show], constraints: { id: %r{[^/]+} } do
      member do
        post :sync
        post :commit_create
        get :commits
      end
    end

    resources :pull_requests, only: [:index, :show] do
      member do
        post :sync
        post :commit_create
        get :commits
      end
    end

    resources :proposals
  end
  resource :connections, only: :show do
    get "/github/callback", to: "connections#github_callback"
    delete :disconnect_github
    post :request_sync
  end

  authenticate :user, ->(user) { user.admin? } do
    mount GoodJob::Engine => "good_job"
  end
end

app/models/project_invitation.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: project_invitations
#
#  id          :bigint           not null, primary key
#  accepted_at :datetime
#  email       :string
#  token       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  project_id  :bigint           not null
#
# Indexes
#
#  index_project_invitations_on_project_id  (project_id)
#
# Foreign Keys
#
#  fk_rails_...  (project_id => projects.id)
#
class ProjectInvitation < ApplicationRecord
  belongs_to :project
  has_secure_token

  # TODO: review the email validation
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  scope :pending, -> { where(accepted_at: nil) }

  def status
    accepted_at.present? ? :accepted : :pending
  end

  def accept!(user)
    transaction do
      project.users << user
      self.accepted_at = Time.current
      save!
    end
  end
end

app/controllers/project_invitations_controller.rb
# frozen_string_literal: true

class ProjectInvitationsController < ApplicationController
  before_action :find_project!

  def index
    @invitations = @project.invitations.page(params[:page])
  end

  def new
    @invitation = @project.invitations.build
  end

  def create
    @invitation = @project.invitations.build(invitation_params)
    if @invitation.save
      ProjectMailer.with(invitation: @invitation).invitation_email.deliver_later
      redirect_to project_invitations_path(@project), notice: "Invitation sent"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def find_project!
    @project = current_user.projects.find_by!(slug: params[:project_id])
  end

  def invitation_params
    params.require(:project_invitation).permit(:email)
  end
end

app/views/project_invitations/index.html.haml
.d-flex.justify-content-between.align-items-center.mb-4
  %nav{"aria-label" => "breadcrumb"}
    %ol.breadcrumb
      %li.breadcrumb-item
        = link_to "Projects", projects_path
      %li.breadcrumb-item
        = link_to @project.name, project_path(@project)
      %li.breadcrumb-item
        = link_to "Members", project_members_path(@project)
      %li.breadcrumb-item.active{"aria-current" => "page"} Invitations

  .links
    = link_to "New invitation", new_project_invitation_path(@project), class: 'btn btn-primary'

- if @invitations.any?
  %table.table.table-hover
    %thead
      %tr
        %th Email
        %th Invited at
        %th Status
        %th Actions
    %tbody
      - @invitations.each do |invitation|
        %tr
          %td= invitation.email
          %td= invitation.created_at
          %td= invitation.status
          %td= button_to "delete", project_invitation_path(@project, invitation), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm'
- else
  %p.lead
    No invitations have been sent yet.
    %br
    = link_to 'Invite someone', new_project_invitation_path(@project), class: 'btn btn-primary btn-lg'

app/views/project_invitations/new.html.haml
.d-flex.justify-content-between.align-items-center
  %nav{"aria-label" => "breadcrumb"}
    %ol.breadcrumb
      %li.breadcrumb-item
        = link_to "Projects", projects_path
      %li.breadcrumb-item
        = link_to @project.name, project_path(@project)
      %li.breadcrumb-item
        = link_to "Members", project_members_path(@project)
      %li.breadcrumb-item
        = link_to "Invitations", project_invitations_path(@project)
      %li.breadcrumb-item.active{"aria-current" => "page"} New Invitation


= simple_form_for @invitation do |f|
  = f.input :email, label: 'Email address'
  = f.button :submit, class: 'btn btn-primary'