config/routes.rb
# frozen_string_literal: true

# == Route Map
#

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "projects#index"

  resources :projects do
    member do
      post :sync
      get :configure
    end

    collection do
      get :user
    end

    resources :members, only: %i[index], controller: "project_members"
    resources :invitations, only: %i[index new create destroy], controller: "project_invitations"
    resource :accept_invitations, only: [:show], controller: "project_accept_invitations" do
      member do
        post :join
      end
    end

    resources :branches, only: [:index, :show], constraints: { id: %r{[^/]+} } do
      member do
        post :sync
        post :commit_create
        get :commits
      end
    end

    resources :pull_requests, only: [:index, :show] do
      member do
        post :sync
        post :commit_create
        get :commits
      end
    end

    resources :proposals
  end
  resource :connections, only: :show do
    get "/github/callback", to: "connections#github_callback"
    delete :disconnect_github
    post :request_sync
  end

  authenticate :user, ->(user) { user.admin? } do
    mount GoodJob::Engine => "good_job"
  end
end

app/models/project.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: projects
#
#  id                             :bigint           not null, primary key
#  allow_remote_contributors      :boolean          default(FALSE), not null
#  config_from_repo               :json
#  default_branch_name            :string
#  default_locale                 :string
#  github_access_token            :string
#  github_access_token_expires_at :datetime
#  name                           :string
#  public                         :boolean          default(FALSE)
#  recognized                     :boolean          default(FALSE), not null
#  repo_public                    :boolean          default(FALSE), not null
#  setup_status                   :integer          default("pending"), not null
#  slug                           :string
#  translations_path              :string
#  use_config_from_repo           :boolean          default(FALSE), not null
#  created_at                     :datetime         not null
#  updated_at                     :datetime         not null
#  installation_id                :string
#  remote_repository_id           :string
#
# Indexes
#
#  index_projects_on_slug  (slug) UNIQUE
#
class Project < ApplicationRecord
  include Syncable

  enum :setup_status, { pending: 0, config_fetched: 1 }, prefix: true

  encrypts :github_access_token

  has_one :metadata, class_name: "MetadataProject", dependent: :delete
  lazy_has_one :metadata

  has_many :invitations, class_name: "ProjectInvitation", dependent: :delete_all
  has_many :memberships, dependent: :delete_all
  has_many :users, through: :memberships

  has_many :branches, dependent: :delete_all
  has_one :default_branch, ->(x) { where(name: x.default_branch_name) }, class_name: "Branch"
  lazy_has_one :default_branch

  has_many :translations, dependent: :delete_all
  has_many :proposals, dependent: :delete_all
  has_many :pull_requests, dependent: :delete_all
  has_many :commit_tasks, dependent: :delete_all

  validates :remote_repository_id, presence: true
  validates :slug, uniqueness: true, presence: true

  before_validation :set_slug, on: :create

  broadcasts_refreshes

  def installation_remote_repository_id
    [installation_id, remote_repository_id].join(":")
  end

  def installation_remote_repository_id=(value)
    self.installation_id, self.remote_repository_id = value.split(":")
  end

  def to_param
    slug
  end

  def set_slug
    self.slug ||= "#{SecureRandom.base36}-#{slug_for_repo}"
  end

  def slug_for_repo
    @slug_for_repo ||= begin
      user, repo = remote_repository_id.split("/")
      "github:#{user}:#{repo}"
    end
  end

  # START: cosmetic defaults
  # We could get rid of this
  def name
    super.presence || remote_repository_id
  end

  def client
    @client ||= ProjectGithubClientProxy.new(self, authentication)
  end

  def authentication
    @authentication ||= if installation_id
                          InstallationGithubAuthentication.new(self)
                        else
                          # TODO: we should probably not use the first user
                          # but the owner of the project.
                          # This is a temporary solution
                          UserGithubAuthentication.new(users.first)
                        end
  end

  def stats
    @stats ||= ProjectStats.new(self)
  end

  def url
    File.join(Babelfu.config.github_domain, remote_repository_id)
  end

  def enqueue_fetch_config!
    FetchProjectConfigJob.perform_later(self)
  end

  def config_fetched!
    update!(setup_status: "config_fetched")
  end

  def enqueue_sync_data!
    sync_in_progress!
    SyncProjectJob.perform_later(self)
  end

  def collaborator?(user)
    metadata.github_collaborators.any? { |c| c["login"] == user.github_username && c.dig("permissions", "push") }
  end

  def existing_recognized_repo
    Project.find_by(slug: slug_for_repo)
  end

  def frontend_attrs
    {
      allow_remote_contributors:,
      config_from_repo:,
      default_branch_name:,
      default_locale:,
      name:,
      public:,
      recognized:,
      repo_public:,
      setup_status:,
      slug:,
      translations_path:,
      use_config_from_repo:,
      remote_repository_id:,
      existing_recognized_repo:,
      url:
    }
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show sync]
  after_action :verify_authorized

  def index
    authorize Project
    @projects = Project.where(public: true, recognized: true).page(params[:page])
  end

  def user
    authorize Project
    @projects = current_user.projects.page(params[:page])
  end

  def show
    find_project
    authorize @project, :explore?
    @pull_requests = @project.pull_requests.limit(10).order(updated_at: :desc)
    @branches = @project.branches.limit(10).order(updated_at: :desc)
  end

  def new
    authorize Project, :create?
    redirect_to connections_path, alert: "You need to connect to GitHub first." if current_user.github_access_token.blank?
    @project = current_user.projects.build
  end

  def edit
    find_project
    authorize @project, :update?
  end

  def create
    authorize Project, :create?
    @project = current_user.projects.build(project_params)
    if @project.save
      current_user.projects << @project
      @project.enqueue_fetch_config!
      # @project.enqueue_sync_data!
      redirect_to configure_project_path(@project), notice: "Project was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def configure
    find_project
    authorize @project, :update?
  end

  def sync
    find_project
    authorize @project, :sync?
    @project.enqueue_sync_data!
    redirect_to project_path(@project), notice: "Project is being synced."
  end

  def update
    find_project
    authorize @project, :update?

    if @project.update(project_params)
      @project.enqueue_sync_data!
      redirect_to project_path(@project), notice: "Project was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    find_project
    authorize @project

    @project&.destroy
    redirect_to projects_path, notice: "Project was successfully destroyed."
  end

  private

  def find_project
    @project = Project.find_by!(slug: params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :installation_remote_repository_id, :default_locale, :translations_path, :public, :allow_remote_contributors)
  end
end

app/views/projects/configure.html.haml
%h1 Configure #{@project.remote_repository_id}

= link_to "github repo", @project.url

- if @project.setup_status_pending?
  %p.lead
    We are fetching the repository information. Try refreshing the page in a few seconds.
- if @project.setup_status_config_fetched?
  %dl
    %dt Default branch
    %dd= @project.default_branch_name
    %dt Config on repo available
    %dd
      - if @project.config_from_repo.present?
        = @project.config_from_repo
        // TODO: check if there is already a recognized project
        // only one project can be recognized

    %dt Exsiting recognized project
    %dd
      - if @project.existing_recognized_repo.present?
        = link_to @project.remote_repository_id, projects_path(@project.existing_recognized_repo)
      - else
        No recognized project found

- if @project.repo_public? && @project.config_from_repo? && @project.existing_recognized_repo.blank?
  %p.lead
    This repo is public
    %br
    It has a config file
    %br
    It is not recognized by any project, so you can make it recognized.

= turbo_mount("ConfigureProject", props: {project: @project.frontend_attrs}, class: "mb-5")

app/views/projects/edit.html.haml
.d-flex.justify-content-between.align-items-center
  %nav{"aria-label" => "breadcrumb"}
    %ol.breadcrumb
      %li.breadcrumb-item
        = link_to "Projects", projects_path
      %li.breadcrumb-item
        = link_to @project.name, project_path(@project)
      %li.breadcrumb-item.active{"aria-current": "page"}
        Edit

= simple_form_for @project do |f|
  = f.input :name
  = f.input :default_locale
  = f.input :translations_path, hint: "Path to the translations files", placeholder: "config/locales"
  = f.input :public, as: :boolean, hint: "If the project is public, it will be visible to everyone"
  = f.input :allow_remote_contributors, as: :boolean, hint: "Allow access to the project to any repository collaborator"
  = f.button :submit, class: "btn btn-primary"

app/views/projects/index.html.haml
.d-flex.justify-content-between.align-items-center
  %h1 Projects
  .actions.d-flex.flex-row.align-items-end
    - if policy(Project).create?
      = link_to 'New Project', new_project_path

- @projects.each do |project|
  .card.mb-3
    .card-header
      .d-flex.justify-content-between.align-items-center
        = link_to project.remote_repository_id, project_path(project)
        %span
          .d-flex.justify-content-between.align-items-center
            - if project.public?
              %span.badge.bg-primary
                Public
            - else
              %span.badge.bg-danger
                Private
            .ms-2
              = render GithubLinkComponent.new(project.url)
    .card-body
      .d-flex.justify-content-between
        .data
          .keys
            %strong Keys:
            = project.stats.total_keys
          .percent-translated
            %strong Done:
            = "#{project.stats.total_percent_translated.ceil}%"
          .locales
            %strong Locales:
            = project.stats.locales.count
        .actions
          = link_to "edit", edit_project_path(project), class: 'btn btn-sm btn-outline-primary' if policy(project).update?
      .container.mt-3
        .row.row-cols-xl-5.row-cols-lg-4.row-cols-md-3.row-cols-2
          - project.stats.locales.each do |locale_stats|
            .col
              .border.border-2.rounded-3.p-2.m-1
                %small= locale_stats.locale.upcase
                .progress{"aria-label" => "Progress completed #{locale_stats.locale}", "aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => locale_stats.percent_translated.ceil, :role => "progressbar", :style => "height: 1px"}
                  .progress-bar{:style => "width: #{locale_stats.percent_translated.ceil}%"}
                %small
                  = "DONE #{locale_stats.percent_translated.ceil} %"
= paginate @projects, theme: 'bootstrap-5'

app/views/projects/new.html.haml
.d-flex.justify-content-between.align-items-center
  %nav{"aria-label" => "breadcrumb"}
    %ol.breadcrumb
      %li.breadcrumb-item
        = link_to "Projects", projects_path
      %li.breadcrumb-item.active{"aria-current": "page"}
        New Project

.row
  .col-md-6.col-md-offset-3
    = simple_form_for @project do |f|
      = f.input :installation_remote_repository_id, collection: current_user.github_remote_repositories_for_select, label: "Github Repository", hint: connect_to_github_message
      = f.button :submit, class: "btn btn-primary"

app/views/projects/show.html.haml
= turbo_stream_from @project
.d-flex.justify-content-between.align-items-center
  %nav{"aria-label" => "breadcrumb"}
    %ol.breadcrumb
      %li.breadcrumb-item
        = link_to "Projects", projects_path
      %li.breadcrumb-item.active{"aria-current": "page"}
        = @project.name
  .actions.d-flex.flex-row.align-items-end
    = render GithubLinkComponent.new(@project.url)
    - if policy(@project).sync?
      .ms-5= render SyncProjectWidgetComponent.new(@project)

.d-flex.justify-content-between.align-items-center
  %h1.fs-3.mb-0= @project.name
  .links
    = link_to "edit", edit_project_path(@project) if policy(@project).update?
    = link_to "members", project_members_path(@project) if policy(@project).list_members?

- if @project.default_branch
  %div.mb-3.pt-1
    Default branch:
    %code #{@project.default_branch.name}
    with
    %strong
      #{@project.default_branch.translations.select('key').distinct.count} keys
    and
    %strong
      #{@project.default_branch.translations.select('locale').distinct.count} locales
.row
  .col-md-6
    .d-flex.justify-content-between.align-items-end
      %h2 Pull Requests
      .pb-1= link_to "see all", project_pull_requests_path(@project)
    - if @pull_requests.empty?
      %p No pull requests
    - else
      %ul.list-group
        - @pull_requests.each do |pr|
          %li.list-group-item.d-flex.justify-content-between.align-items-center
            = link_to pr.title, project_pull_request_path(@project, pr), class: 'text-decoration-none'
            = link_to pr.url, target: '_blank' do
              %span.badge.text-bg-primary.rounded-pill
                = pr.state
                %i.bi.bi-box-arrow-up-right

  .col-md-6
    .d-flex.justify-content-between.align-items-end
      %h2 Branches
      .pb-2= link_to "see all", project_branches_path(@project)
    - if @branches.empty?
      %p No branches
    - else
      %ul.list-group
        - @branches.each do |branch|
          %li.list-group-item.d-flex.justify-content-between.align-items-center
            = link_to branch.name, project_branch_path(@project, branch), class: 'text-decoration-none'

app/views/projects/user.html.haml
.d-flex.justify-content-between.align-items-center
  %h1 Projects
  .actions.d-flex.flex-row.align-items-end
    - if policy(Project).create?
      = link_to 'New Project', new_project_path

%table.table
  %thead
    %tr
      %th Name
      %th Actions
  %tbody
    - @projects.each do |project|
      %tr
        %td= link_to project.remote_repository_id, project_path(project)
        %td
          = link_to "edit", edit_project_path(project) if policy(project).update?
          = link_to "delete", project, "data-turbo-method": "delete", "data-turbo-confirm": "Are you sure?" if policy(project).destroy?

= paginate @projects, theme: 'bootstrap-5'