config/routes.rb
# frozen_string_literal: true

# == Route Map
#

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "projects#index"

  resources :projects do
    member do
      post :sync
      get :configure
    end

    collection do
      get :user
    end

    resources :members, only: %i[index], controller: "project_members"
    resources :invitations, only: %i[index new create destroy], controller: "project_invitations"
    resource :accept_invitations, only: [:show], controller: "project_accept_invitations" do
      member do
        post :join
      end
    end

    resources :branches, only: [:index, :show], constraints: { id: %r{[^/]+} } do
      member do
        post :sync
        post :commit_create
        get :commits
      end
    end

    resources :pull_requests, only: [:index, :show] do
      member do
        post :sync
        post :commit_create
        get :commits
      end
    end

    resources :proposals
  end
  resource :connections, only: :show do
    get "/github/callback", to: "connections#github_callback"
    delete :disconnect_github
    post :request_sync
  end

  authenticate :user, ->(user) { user.admin? } do
    mount GoodJob::Engine => "good_job"
  end
end

app/controllers/project_members_controller.rb
# frozen_string_literal: true

class ProjectMembersController < ApplicationController
  before_action :find_project
  after_action :verify_authorized

  def index
    authorize @project, :list_members?
    @users = @project.users.page(params[:page])
  end

  private

  def find_project
    @project = current_user.projects.find_by!(slug: params[:project_id])
  end
end

app/views/project_members/index.html.haml
.d-flex.justify-content-between.align-items-center
  %nav{"aria-label" => "breadcrumb"}
    %ol.breadcrumb
      %li.breadcrumb-item
        = link_to "Projects", projects_path
      %li.breadcrumb-item
        = link_to @project.name, project_path(@project)
      %li.breadcrumb-item.active{"aria-current" => "page"} Members

  .links
    = link_to "Invitations", project_invitations_path(@project)

.row
  .col-6
    %table.table.table-hover
      %thead
        %tr
          %th Email
          %th Github Username
      %tbody
        - @users.each do |user|
          %tr
            %td= user.email
            %td= user.github_username


    = paginate @users, theme: 'bootstrap-5'
  .col-6
    %p.lead
      This is a list of all the members that can access to this project independently of their access level on
      the repository.
    %p.lead
      Additionally collaborators of the repository will be able to access and edit translations to the repository.
    %p.lead
      You can configure this behavoir on the
      = link_to "project settings", edit_project_path(@project)
      \.